### ISSUE TITLE
NoSuchMethodError with Java 8 and Payara 4

### ISSUE THREAD

**Issue by ralfovelgoenne** [microprofile-extensions/openapi-ext#32]
Got the following error on Java 8 with Payara 4:
Caused by: java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()[B
	at org.microprofileext.openapi.swaggerui.Templates.getLogo(Templates.java:121)
	at org.microprofileext.openapi.swaggerui.Templates.afterCreate(Templates.java:46)
	... 78 more

Should it work with Java 8?

**Comment by ralfovelgoenne** [comment]
I did see in the other post: should I use 1.1.3 for Java 8?

**Comment by phillip-kruger** [comment]
Yes :)

**Comment by heinerbilch** [comment]
Is it possible to document this ? I have tried 1.1.4 with JBoss 7 and JDK 8 and failed :) 1.1.3 works fine. It was a litte surprise 1.1.4 didn't work, because the jar can be loaded with JDK8 (but not run).

**Comment by phillip-kruger** [comment]
We accept PRs :)
