### ISSUE TITLE
Swagger UI not generated

### ISSUE THREAD

**Issue by dekaido** [microprofile-extensions/openapi-ext#41]
Hi, I posted [this issue](https://stackoverflow.com/questions/70396508/add-swagger-ui-for-microprofile-openapi) in SO and have no responses. Hope I can get some guidance here to see if this is an issue on my end.

---
*Related to [How to make OpenApi UI work in Payara Micro](https://stackoverflow.com/questions/60563948/how-to-make-openapi-ui-work-in-payara-micro)- but I'm looking for an answer...*

I followed all of the instructions and tried to use this [openapi-ui extension](https://github.com/microprofile-extensions/openapi-ext/blob/main/openapi-ui/README.md) to generate a  UI for my REST endpoints based on my existing [Eclipse Microprofile OpenAPI](https://download.eclipse.org/microprofile/microprofile-open-api-1.1.2/microprofile-openapi-spec.html) annotations. According to the README and tutorials of this extension, the Swagger UI should be automatically generated with an `index.html` at `https://<ip-port>/<endpoint>/openapi-ui`. However, it is not and I am only able to access the regular `/openapi` page.

I am using Gradle, so I am importing the Maven library like this:
``` java
providedCompile group: 'org.microprofile-ext.openapi-ext', name: 'openapi-ui', version: '1.1.5'
```

Like aforementioned question, I am also using Angular frontend, Jakarta EE backend, Payara Microservices.

Can anyone help me understand what the issue is, or suggest another way to implement the Swagger UI in my project?

**Comment by phillip-kruger** [comment]
Can you share a reproducer

**Comment by dekaido** [comment]
@phillip-kruger As in a project to reproduce the issue?

**Comment by phillip-kruger** [comment]
@dekaido yes please !!

**Comment by dekaido** [comment]
@phillip-kruger Ah, it's a slightly intensive project behind company rules, I won't be able to... nor do I know how to... But if you have any suggestions for me to debug or check anything, I can on my end :/

**Comment by rsoika** [comment]
I think there is in deed an issue regarding newer Microprofile versions and also a problem when you run your microservice in Jakarta EE9 with the new namespace jakarta.* instead of javax.*

For example in latest payara-micro running with jakarta ee 8 the version 1.3 works fine but not 1.4 and 1.5

As there are no release notes in the project it is hard to understand what is going on in this project. I don't want to fork the project if someone is already working on this issue?

**Comment by rsoika** [comment]
Running version 1.5 in payara-micro:5.2021.10 did cause the following exception whenn opening the page  `/openapi-ui/index.html `

```
[2022-01-12T16:48:04.422+0000] [] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=66 _ThreadName=http-thread-pool::http-listener(1)] [timeMillis: 1642006084422] [levelValue: 900] [[
  StandardWrapperValve[com.ralph.BaseApplication]: Servlet.service() for servlet com.ralph.BaseApplication threw exception
java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()[B
	at org.microprofileext.openapi.swaggerui.Templates.getLogo(Templates.java:125)
	at org.microprofileext.openapi.swaggerui.Templates.afterCreate(Templates.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:83)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:66)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:164)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)
	at org.microprofileext.openapi.swaggerui.Templates$Proxy$_$$_WeldClientProxy.getSwaggerUIHtml(Unknown Source)
	at org.microprofileext.openapi.swaggerui.OpenApiUiService.getOpenApiUI(OpenApiUiService.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:259)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
]]
```

**Comment by rsoika** [comment]
ok, after all I came across that the issue may be caused by the JDK  - version 11 is expected.
So if you run your server for example with payara docker image use the JDK 11 version

     payara/micro:5.2021.10-jdk11

This will solve the issues and swagger ui is working again.
